name: Pull-Request

on: pull_request

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Restore tools
        run: dotnet tool restore

      - name: Build
        run: dotnet build -c Release

      - name: Capture Coverage
        shell: pwsh
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          $coverageFiles = Get-ChildItem -Path . -Recurse -Filter coverage.cobertura.xml
          $coveragePaths = $coverageFiles | ForEach-Object { $_.FullName }
          $reportsArg = '"' + ($coveragePaths -join ";") + '"'
          dotnet tool run reportgenerator -reports:$reportsArg "-targetdir:coverage-report" "-filefilters:-*.g.cs" "-reporttypes:Html"

      - name: Upload Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report

      - name: Mutation testing
        run: |
          dotnet tool restore
          dotnet stryker --since:main

      - name: Upload Stryker Report
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: StrykerOutput
